container:
  image: termux/package-builder:latest
  cpu: 8
  memory: 16

# Build packages.
build_task:
  # 2 hours is a maximal timeout for free use.
  timeout_in: 120m

  environment:
    matrix:
      TERMUX_ARCH: aarch64
      TERMUX_ARCH: arm
      TERMUX_ARCH: i686
      TERMUX_ARCH: x86_64

  # Do not use built-in git client provided by Cirrus as it
  # causes problems when determining changed files.
  clone_script: |
    if [[ -z "$CIRRUS_PR" ]]; then
      git clone --recursive --branch="$CIRRUS_BRANCH" "https://x-access-token:${CIRRUS_REPO_CLONE_TOKEN}@github.com/${CIRRUS_REPO_FULL_NAME}.git" "$CIRRUS_WORKING_DIR"
      git reset --hard "$CIRRUS_CHANGE_IN_REPO"
    else
      git clone --recursive "https://x-access-token:${CIRRUS_REPO_CLONE_TOKEN}@github.com/${CIRRUS_REPO_FULL_NAME}.git" "$CIRRUS_WORKING_DIR"
      git fetch origin "pull/$CIRRUS_PR/head:pull/$CIRRUS_PR"
      git reset --hard "$CIRRUS_CHANGE_IN_REPO"
    fi

  # Copy packages into 'termux-packages' build environment.
  prepare_script: |
    for pkg in ./packages/*; do
        if [ ! -d "./termux-packages/packages/$(basename "$pkg")" ]; then
            cp -a "$pkg" ./termux-packages/packages/
        else
            echo "[!] Package '$(basename "$pkg")' already exists in build environment. Skipping."
        fi
    done

  # Determine changes in repository and build modified packages.
  build_script: |
    if grep -qiP '^\s*%ci:reset-backlog\s*$' <(git log --format="%B" -n 1 "$CIRRUS_CHANGE_IN_REPO"); then
        # If commit message contains line '%ci:reset-backlog', builds will be done
        # only for current commit.
        unset CIRRUS_LAST_GREEN_CHANGE
        unset CIRRUS_BASE_SHA
    fi
    MODIFIED_PACKAGES=$(./scripts/get-modified-packages.sh)
    cd ./termux-packages
    for package in $MODIFIED_PACKAGES; do
        if [ -n "$CIRRUS_PR" ]; then
            # Perform full builds for PR.
            ./build-package.sh -a "$TERMUX_ARCH" "$package"
        else
            ./build-package.sh -I -a "$TERMUX_ARCH" "$package"
        fi
    done
    if [ -d ./debs ]; then
        # Upload packages to cache.
        tar zcf "debs-${TERMUX_ARCH}.tar.gz" debs
        curl -s --upload-file "debs-${TERMUX_ARCH}.tar.gz" "http://$CIRRUS_HTTP_CACHE_HOST/debs-${TERMUX_ARCH}-${CIRRUS_CHANGE_IN_REPO}"
    fi

  # Make packages downloadable via UI.
  output_artifacts:
    path: "./termux-packages/debs/*.deb"

# Publish packages to Bintray.
publish_task:
  only_if: $CIRRUS_BRANCH == 'master' || $CIRRUS_BRANCH == 'android-5'

  timeout_in: 60m

  depends_on:
    - build

  environment:
    BINTRAY_USERNAME: ENCRYPTED[]
    BINTRAY_API_KEY: ENCRYPTED[]

  upload_to_bintray_script: |
    if grep -qiP '^\s*%ci:reset-backlog\s*$' <(git log --format="%B" -n 1 "$CIRRUS_CHANGE_IN_REPO"); then
        unset CIRRUS_LAST_GREEN_CHANGE
        unset CIRRUS_BASE_SHA
    fi
    MODIFIED_PACKAGES=$(./scripts/get-modified-packages.sh)
    if [ -n "$MODIFIED_PACKAGES" ]; then
        for arch in aarch64 arm i686 x86_64; do
            curl -s -o "/tmp/debs-${arch}.tar.gz" "http://$CIRRUS_HTTP_CACHE_HOST/debs-${arch}-${CIRRUS_CHANGE_IN_REPO}"
            tar xvf "/tmp/debs-${arch}.tar.gz"
            rm -f "/tmp/debs-${arch}.tar.gz"
        done
        ./scripts/package_uploader.sh $MODIFIED_PACKAGES
    fi
